# Generated by Django 5.0.6 on 2024-06-15 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_alter_prescription_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="gcs",
            field=models.ForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="management.gcs",
            ),
        ),
    ]
