# Generated by Django 5.0.6 on 2024-06-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_prescription_gcs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="dosage",
        ),
    ]
