# Generated by Django 5.0.6 on 2024-06-21 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_remove_prescription_dosage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="medication_names",
        ),
        migrations.AlterField(
            model_name="delivery",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="Medication",
        ),
    ]
