# Generated by Django 5.0.6 on 2024-06-21 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_remove_prescription_medication_names_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1c071818-d99a-4169-b987-95c4f82c83bc"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="drone",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
